apiVersion: v1
kind: ConfigMap
metadata:
  name: a1conf
data:
  local.rt: |
    newrt|start
    rte|20000|testreceiverrmrservice:4560
    rte|20002|testreceiverrmrservice:4560
    rte|21024|{{ .Values.rmrservice.name }}:{{ .Values.rmrservice.port }}
    newrt|end
  rmr_string_int_mapping.txt: {{ tpl (.Files.Get "files/rmr_string_int_mapping.txt") . | quote }}
  ricmanifest.json: {{ tpl (.Files.Get "files/ricmanifest.json") . | quote }}
