apiVersion: v1
kind: ConfigMap
metadata:
  name: a1conf
data:
  local.rt: |
    newrt|start
    rte|20000|testreceiverrmrservice:4560
    rte|20001|delayreceiverrmrservice:4563
    # purposefully bad route to make sure rmr doesn't block on non listening receivers:
    rte|20002|testreceiverrmrservice:4563
    newrt|end
