apiVersion: v1
kind: ConfigMap
metadata:
  name: a1conf
data:
  local.rt: |
    newrt|start
    rte|20000|testreceiverrmrservice:4560
    rte|20001|delayreceiverrmrservice:4563
    rte|21024|{{ .Values.rmrservice.name }}:{{ .Values.rmrservice.port }}
    newrt|end
