apiVersion: v1
kind: ConfigMap
metadata:
  name: delayreceiverconf
data:
  local.rt: |
    newrt|start
    rte|10000|{{ .Values.rmrservice.name }}:{{ .Values.rmrservice.port }}
    rte|10001|a1rmrservice:4562
    newrt|end

