replicaCount: 1

image:
  repository: nexus3.o-ran-sc.org:10004/ric-plt-a1
  tag: 0.8.2
  pullPolicy: IfNotPresent

imageCredentials:
  registry: nexus3.o-ran-sc.org:10004/ric-plt-a1
  username:
  password:

httpservice:
  port: 10000 ## dont change this!!
  type: ClusterIP

rmrservice:
  name: rmrservice
  port: 4562 ## dont change this!!
  type: ClusterIP



RMR_RCV_RETRY_INTERVAL: 500
RMR_RETRY_TIMES: 20

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
