# test_a1.tavern.yaml

test_name: test healthcheck

stages:
  - name: test the a1 healthcheck
    request:
      url: http://localhost:10000/a1-p/healthcheck
      method: GET
    response:
      status_code: 200


---

test_name: test delayed policy

stages:
  - name: test the delayed policy
    request:
      url: http://localhost:10000/ric/policies/test_policy
      method: PUT
      json:
        {}
      headers:
        content-type: application/json
    response:
      status_code: 200
      body:
        ACK_FROM: DELAYED_TEST
        status: SUCCESS


---

test_name: test admission control

stages:
  - name: test the admission control policy
    request:
      url: http://localhost:10000/ric/policies/admission_control_policy
      method: PUT
      json:
        enforce: true
        window_length: 10
        blocking_rate: 20
        trigger_threshold: 10
      headers:
        content-type: application/json
    response:
      status_code: 200
      body:
        ACK_FROM: ADMISSION_CONTROL
        status: SUCCESS

  - name: test the admission control policy get
    request:
      url: http://localhost:10000/ric/policies/admission_control_policy
      method: GET
    response:
      status_code: 200
      body:
        mock return from FETCH: pretend policy is here

---

test_name: bad_requests

stages:
  - name: does not exist
    request:
      url: http://localhost:10000/ric/policies/darkness
      method: PUT
      json:
        {}
      headers:
        content-type: application/json
    response:
      status_code: 404

  - name: bad body for admission control policy
    request:
      url: http://localhost:10000/ric/policies/admission_control_policy
      method: PUT
      json:
        not: "expected"
      headers:
        content-type: application/json
    response:
      status_code: 400

  - name: not a json
    request:
      url: http://localhost:10000/ric/policies/admission_control_policy
      method: PUT
      data: "asdf"
    response:
      status_code: 415

  - name: bad body for test policy
    request:
      url: http://localhost:10000/ric/policies/test_policy
      method: PUT
      json:
        not: "welcome"
    response:
      status_code: 400

  - name: test policy doesnt support fetch
    request:
      url: http://localhost:10000/ric/policies/test_policy
      method: GET
    response:
      status_code: 400
