apiVersion: v1
kind: ConfigMap
metadata:
  name: testreceiverconf
data:
  local.rt: |
    newrt|start
    rte|20000|{{ .Values.rmrservice.name }}:{{ .Values.rmrservice.port }}
    rte|20001|a1rmrservice:4562
    newrt|end

