apiVersion: v1
kind: ConfigMap
metadata:
  name: testreceiverconf
data:
  local.rt: |
    newrt|start
    rte|20000|{{ .Values.testrmrservice.name }}:{{ .Values.testrmrservice.port }}
    rte|21024|a1rmrservice:4562
    newrt|end

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: delayreceiverconf
data:
  local.rt: |
    newrt|start
    rte|20001|{{ .Values.delayrmrservice.name }}:{{ .Values.delayrmrservice.port }}
    rte|21024|a1rmrservice:4562
    newrt|end
