apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "testreceiver.fullname" . }}
  labels:
{{ include "testreceiver.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "testreceiver.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "testreceiver.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        #query receiver
        - name: queryreceiver
          image: queryreceiver:latest
          imagePullPolicy: Never
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: queryreceiverconf
              mountPath: /opt/route/local.rt
              subPath: local.rt

        # test receiver
        - name: testreceiver
          image: testreceiver:latest
          imagePullPolicy: Never
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: testreceiverconf
              mountPath: /opt/route/local.rt
              subPath: local.rt

        # test receiver that delays until sending
        - name: delayreceiver
          image: testreceiver:latest
          imagePullPolicy: Never
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: delayreceiverconf
              mountPath: /opt/route/local.rt
              subPath: local.rt
          env:
          - name: TEST_RCV_PORT
            value: "{{ .Values.delayrmrservice.port }}"
          - name: TEST_RCV_SEC_DELAY
            value: "5"
          - name: HANDLER_ID
            value: "delay_receiver"

      volumes:
        - name: "testreceiverconf"
          configMap:
            name: "testreceiverconf"
        - name: "delayreceiverconf"
          configMap:
            name: "delayreceiverconf"
        - name: "queryreceiverconf"
          configMap:
            name: "queryreceiverconf"
