apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rmrservice.name }}
  labels:
{{ include "testreceiver.labels" . | indent 4 }}
spec:
  type: {{ .Values.rmrservice.type }}
  ports:
    - port: {{ .Values.rmrservice.port }}
      targetPort: {{ .Values.rmrservice.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "testreceiver.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
