apiVersion: v1
kind: ConfigMap
metadata:
  name: a1conf
data:
  local.rt: |
    newrt|start
    rte|10000|rmr_delay_receiver:4563
    rte|20000|rmr_receiver:4560
    rte|10001|{{ .Values.rmrservice.name }}:{{ .Values.rmrservice.port }}
    rte|20001|{{ .Values.rmrservice.name }}:{{ .Values.rmrservice.port }}
    newrt|end
  rmr_string_int_mapping.txt: |
    DC_ADMISSION_INTERVAL_CONTROL:20000
    DC_ADMISSION_INTERVAL_CONTROL_ACK:20001
    TEST_REQ:10000
    TEST_ACK:10001
  ricmanifest.json: |
    {
      "controls":[
        {
          "name":"control_admission_time",
          "description":"time period to allow dual connection",
          "message_receives_rmr_type":"DC_ADMISSION_INTERVAL_CONTROL",
          "message_receives_payload_schema":{
            "$schema":"http://json-schema.org/draft-07/schema#",
            "type":"object",
            "properties":{
              "dc_admission_start_time":{
                "type":"string",
                "pattern":"^[0-9]{2}:[0-9]{2}:[0-9]{2}$"
              },
              "dc_admission_end_time":{
                "type":"string",
                "pattern":"^[0-9]{2}:[0-9]{2}:[0-9]{2}$"
              }
            },
            "required":[
              "dc_admission_start_time",
              "dc_admission_end_time"
            ]
          },
          "message_sends_rmr_type":"DC_ADMISSION_INTERVAL_CONTROL_ACK",
          "message_sends_payload_schema":{
            "$schema":"http://json-schema.org/draft-07/schema#",
            "type":"object",
            "properties":{
              "status":{
                "type":"string",
                "enum":[
                  "SUCCESS",
                  "FAIL"
                ]
              },
              "message":{
                "type":"string"
              }
            }
          }
        },
        {
          "name":"test_policy",
          "description":"for the purposes of testing",
          "message_receives_rmr_type":"TEST_REQ",
          "message_sends_rmr_type":"TEST_ACK",
          "message_sends_payload_schema":{
            "$schema":"http://json-schema.org/draft-07/schema#",
            "type":"object",
            "properties":{
              "status":{
                "type":"string",
                "enum":[
                  "SUCCESS",
                  "FAIL"
                ]
              }
            }
          }
        }
      ]
    }
