apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "a1mediator.fullname" . }}
  labels:
{{ include "a1mediator.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "a1mediator.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "a1mediator.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: myregistrykey
      containers:
        - name: {{ .Chart.Name }}
          volumeMounts:
          - name: ricmanifest-volume
            mountPath: /opt/ricmanifest.json
            subPath: ricmanifest.json
          - name: ricmapping-volume
            mountPath: /opt/rmr_string_int_mapping.txt
            subPath: rmr_string_int_mapping.txt
          - name: rmr-volume
            mountPath: /opt/route/local.rt
            subPath: local.rt
          env:
          - name: PYTHONUNBUFFERED
            value: "0"
          - name: RMR_RCV_RETRY_INTERVAL
            value: "{{ .Values.RMR_RCV_RETRY_INTERVAL}}"
          - name: RMR_RETRY_TIMES
            value: "{{ .Values.RMR_RETRY_TIMES}}"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.httpservice.port }}
              protocol: TCP

          livenessProbe:
            httpGet:
              path: /ui
              port: http
          readinessProbe:
            httpGet:
              path: /ui
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: "ricmanifest-volume"
          configMap:
            name: "ricmanifest"
        - name: "ricmapping-volume"
          configMap:
            name: "rmrmapping"
        - name: "rmr-volume"
          configMap:
            name: "rmrroute"

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
